### ISSUE TITLE
Some  errors when run the basic case  

### ISSUE THREAD

**Issue by ty0402** [yuneg11/SupNotMIWAE-with-ObsDropout#1]
1. which one  is the env you use? If I use the env created by the requirements.txt, there will be some errors about "keras". Then i check the packagelist.txt and finally correct it.  Please tell it clearly.
2.  It seems that the file physionet/SupNotMIWAE.yaml doesn't have 2 required positional arguments: 'output_activation' and 'output_dims'. Are you sure it is correct?

**Comment by yuneg11** [comment]
Thank you for your interest in our research.

1. We actually set up our environment based on the `requirements.txt`, but we backed up the versions of all the packages in the `packagelist.txt`, just in case there were any problems with package versions. If your environment works well with the `packagelist.txt`, you can just use it. We'll add a note to the README.

2. Those arguments are set manually in [`scripts/train.py#L168-169`](https://github.com/yuneg11/SupNotMIWAE-with-ObsDropout/blob/main/scripts/train.py#L168-L169) (set equal to `dataset.output_activation` and `dataset.output_dims`).
